name: gettext_parser
description: Parse and compile gettext po and mo files with dart
version: 0.0.1
author: Alexander Kozlov <cah4o3@gmail.com>
homepage: https://github.com/cah4a/dart_gettext_parser

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: ^1.3.4
  path: ^1.6.2
